version: '2'
 
services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8083:8083
            - 8084:8084
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always
 
    apache:
        depends_on:
            - reverseproxy
        image: httpd:alpine
        restart: always